name: h501-main
dependencies:
  - python=3.11
  - pip
  - pip:
    - ipykernel  # for Jupyter Notebook
    - streamlit
    - seaborn
    - pandas
    - joblib
    - numpy
    - python-dotenv
    - requests
    - tqdm